<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="DasNOCGetBalanceInfo"
     targetNamespace="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/DasNOCGetBalanceInfo"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:WL5G3N1="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/DasNOCGetBalanceInfo"
    >
    <plnk:partnerLinkType name="DasNOCGetBalanceInfo">
        <plnk:role name="DasNOCGetBalanceInfoPort" portType="WL5G3N1:DasNOCGetBalanceInfoPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/DasNOCGetBalanceInfo"
         location="DasNOCGetBalanceInfo.wsdl"/>
</wsdl:definitions>
