<?binding.jca DBAuspice_db.jca?>
<wsdl:definitions name="DBAuspice"
                  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DrCable_SOA/DrCable/DBAuspice"
                  xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DBAuspice"
                  xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DrCable_SOA/DrCable/DBAuspice"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DBAuspice_plt">
        <plt:role name="DBAuspice_role">
            <plt:portType name="tns:DBAuspice_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBAuspice"
                    schemaLocation="xsd/DBAuspice.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DBAuspiceInput_msg">
        <wsdl:part name="DBAuspiceInput_msg" element="db:DBAuspiceInput"/>
    </wsdl:message>
    <wsdl:message name="DBAuspiceOutputCollection_msg">
        <wsdl:part name="DBAuspiceOutputCollection"
                   element="db:DBAuspiceOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBAuspice_ptt">
        <wsdl:operation name="DBAuspice">
            <wsdl:input message="tns:DBAuspiceInput_msg"/>
            <wsdl:output message="tns:DBAuspiceOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>


