<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GetDiagnosticTel_DS"
     targetNamespace="http://xmlns.oracle.com/GetDiagnosticTel/GetDiagnosticTel_DS"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/GetDiagnosticTel/GetDiagnosticTel_DS"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="GetDiagnosticTel.GetDiagnosticTel_DS">
        <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/GetDiagnosticTel/GetDiagnosticTel_DS" location="GetDiagnosticTel_DS.wsdl"/>
</wsdl:definitions>
