<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/DasNOCGetBalanceInfo"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/DasNOCGetBalanceInfo"
	name="DasNOCGetBalanceInfo">
	<types>
		<xsd:schema>
			<xsd:import
				namespace="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/DasNOCGetBalanceInfo"
				schemaLocation="xsd/DasNOCGetBalanceInfo.xsd" />
		</xsd:schema>
	</types>
	<message name="getBalanceInfo">
		<part name="resquest" element="tns:BalanceInfoRequest" />
	</message>
	<message name="getBalanceInfoResponse">
		<part name="response" element="tns:BalanceInfoResponse" />
	</message>
	<portType name="DasNOCGetBalanceInfoPort">
		<operation name="getBalanceInfo">
			<input message="tns:getBalanceInfo" />
			<output message="tns:getBalanceInfoResponse" />
		</operation>
	</portType>
	<binding name="DasNOCGetBalanceInfoPortBinding" type="tns:DasNOCGetBalanceInfoPort">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="getBalanceInfo">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="DasNOCGetBalanceInfo">
		<port name="DasNOCGetBalanceInfoPort" binding="tns:DasNOCGetBalanceInfoPortBinding">
			<soap:address
				location="http://cvsoades:8001/DasNOCGetBalanceInfo/DasNOCGetBalanceInfo" />
		</port>
	</service>
</definitions>