<wsdl:definitions xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
	xmlns:client="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/OrNOCGetMorosidadCte"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	name="OrNOCGetMorosidadCte"
	targetNamespace="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/OrNOCGetMorosidadCte">
	<wsdl:documentation>
		<abstractWSDL>
			http://CVSOADES:8001/soa-infra/services/default/OrNOCGetMorosidadCte!1.0/OrNOCGetMorosidadCte.wsdl
		</abstractWSDL>
	</wsdl:documentation>
	<plnk:partnerLinkType name="OrNOCGetMorosidadCte">
		<plnk:role name="OrNOCGetMorosidadCteProvider" portType="client:OrNOCGetMorosidadCte" />
	</plnk:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import
				namespace="http://xmlns.cablevision.net.mx/DrCable_SOA/DrCable/OrNOCGetMorosidadCte"
				schemaLocation="xsd/OrNOCGetMorosidadCte.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="OrNOCGetMorosidadCteRequestMessage">
		<wsdl:part name="payload" element="client:process" />
	</wsdl:message>
	<wsdl:message name="OrNOCGetMorosidadCteResponseMessage">
		<wsdl:part name="payload" element="client:processResponse" />
	</wsdl:message>
	<wsdl:portType name="OrNOCGetMorosidadCte">
		<wsdl:operation name="process">
			<wsdl:input message="client:OrNOCGetMorosidadCteRequestMessage" />
			<wsdl:output message="client:OrNOCGetMorosidadCteResponseMessage" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OrNOCGetMorosidadCteBinding" type="client:OrNOCGetMorosidadCte">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="process">
			<soap:operation style="document" soapAction="process" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ornocgetmorosidadcte_client_ep">
		<wsdl:port name="OrNOCGetMorosidadCte_pt" binding="client:OrNOCGetMorosidadCteBinding">
			<soap:address
				location="http://cvsoades:8001/soa-infra/services/default/OrNOCGetMorosidadCte/ornocgetmorosidadcte_client_ep" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>